//
// Created by xu fulong on 2022/9/22.
//

#ifndef FFMPEGANDROID_FFPLAY_DEFINE_H
#define FFMPEGANDROID_FFPLAY_DEFINE_H

#define PACKET_QUEUE_SIZE 16

#define FRAME_QUEUE_SIZE 16

#endif //FFMPEGANDROID_FFPLAY_DEFINE_H
