/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "r2.9.6-875-g7d430423d"
#endif /* AVUTIL_FFVERSION_H */
